name: Basic Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Displaying Hello worls
        run: echo "Hello World"
        shell: bash
  Bye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Displaying Good Bye
        run: echo "Good Bye"
        shell: bash